version: "3.3"

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/config/:/etc/nginx/conf.d/
      - ./nginx/log/:/var/log/nginx/
  php:
    image: php:fpm
    ports:
      - "9000:9000"
    volumes:
      - ./php/html/:/var/www/html/
      - ./php/config/site.conf:/usr/local/etc/php/conf.d/site.conf
      - ./php/config/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./php/log/:/var/log/
